In [79]:
import pandas as pd

In [80]:
metadata = pd.read_parquet("../data/raw/movies_metadata.parquet")
metadata

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_language,original_title,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,en,Inception,83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,en,Interstellar,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,en,The Dark Knight,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,en,Avatar,79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,en,The Avengers,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178356,753513,Not a Choice,0.000,0,Released,2016-10-18,0,10,False,None,...,en,Not a Choice,0.600,/xzFKLIzRV6lFA4NykwGcCTTJ23r.jpg,None,None,None,None,None,None
1178363,753524,Westgate Bridge Disaster: The Untold Stories,0.000,0,Released,2020-10-15,0,43,False,/uaspOgPt80wWj7MAIeEGKBiwuFe.jpg,...,en,Westgate Bridge Disaster: The Untold Stories,0.600,/sIYg21mQYVnJjjTQYq1H5KoU7AB.jpg,None,Documentary,"WTFN Entertainment, Had to Be Told Productions...",Australia,English,None
1178364,753525,jazlaansam,0.000,0,Released,None,0,0,False,None,...,en,jazlaansam,0.600,None,jazlaan,None,None,None,None,None
1178366,753532,Costa Brava Heat,0.000,0,Released,2020-10-10,0,110,True,None,...,en,Costa Brava Heat,1.463,/xhebt5nENGXxl5Q5avyAkbvEYJN.jpg,None,None,Private,None,None,None
1178371,753539,Tame Impala live at Glastonbury 2019,0.000,0,Released,2019-06-29,0,89,False,None,...,en,Tame Impala live at Glastonbury 2019,0.601,/2lycWCGDgBvRR97odDy37bMlfV2.jpg,Tame Impala Live at Glastonbury,None,None,None,None,None

In [81]:
len(metadata)

637211

In [82]:
len(set(metadata['id']))

636716

In [83]:
metadata = metadata.drop_duplicates(subset=["id"], keep='first')

In [84]:
len(metadata)

636716

In [85]:
metadata = metadata[metadata['title'] != 'Untitled']
metadata.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_language,original_title,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,en,Inception,83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,en,Interstellar,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,en,The Dark Knight,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,en,Avatar,79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,en,The Avengers,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [86]:
metadata[['keyword_1', 'keyword_2', 'keyword_3', 'keyword_4', 'rest']] = metadata['keywords'].str.split(',', n=4, expand=True)

In [87]:
metadata[['keyword_1', 'keyword_2', 'keyword_3', 'keyword_4']]

             keyword_1   keyword_2       keyword_3           keyword_4
0               rescue     mission           dream            airplane
1               rescue      future      spacecraft   race against time
2                joker      sadism           chaos     secret identity
3               future     society   culture clash        space travel
4        new york city   superhero          shield      based on comic
...                ...         ...             ...                 ...
1178356           None        None            None                None
1178363           None        None            None                None
1178364           None        None            None                None
1178366           None        None            None                None
1178371           None        None            None                None

[636623 rows x 4 columns]

In [88]:
metadata = metadata[metadata['status'] != 'Canceled']

In [89]:
metadata[['genre_1', 'genre_2', 'genre_3', 'genre_4', 'genre_rest']] = metadata['genres'].str.split(',', n=4, expand=True)

In [90]:
metadata.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'popularity',
       'poster_path', 'tagline', 'genres', 'production_companies',
       'production_countries', 'spoken_languages', 'keywords', 'keyword_1',
       'keyword_2', 'keyword_3', 'keyword_4', 'rest', 'genre_1', 'genre_2',
       'genre_3', 'genre_4', 'genre_rest'],
      dtype='object')

In [91]:
metadata[['production_company_1', 'production_company_2', 'production_company_3', 'production_company_4', 'production_company_rest']] = metadata['production_companies'].str.split(',', n=4, expand=True)

In [92]:
metadata.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'popularity',
       'poster_path', 'tagline', 'genres', 'production_companies',
       'production_countries', 'spoken_languages', 'keywords', 'keyword_1',
       'keyword_2', 'keyword_3', 'keyword_4', 'rest', 'genre_1', 'genre_2',
       'genre_3', 'genre_4', 'genre_rest', 'production_company_1',
       'production_company_2', 'production_company_3', 'production_company_4',
       'production_company_rest'],
      dtype='object')

In [93]:
metadata = metadata.drop(columns=["production_company_rest", "genre_rest", "rest", "spoken_languages", "production_companies", "genres", "poster_path", "original_title", "original_language", "imdb_id", "homepage", "backdrop_path"])

In [94]:
metadata[['production_country_1', 'production_country_2', 'production_country_3', 'production_country_rest']] = metadata['production_countries'].str.split(',', n=3, expand=True)

In [95]:
metadata = metadata.drop(columns=["production_country_rest", "keywords", "production_countries"])

In [96]:
metadata[metadata['revenue'] == 0]

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,budget,...,genre_2,genre_3,genre_4,production_company_1,production_company_2,production_company_3,production_company_4,production_country_1,production_country_2,production_country_3
325,405774,Bird Box,6.854,9227,Released,2018-12-13,0,124,False,19800000,...,Thriller,Drama,None,Bluegrass Films,Chris Morgan Productions,None,None,United States of America,None,None
328,791373,Zack Snyder's Justice League,8.190,9202,Released,2021-03-18,0,242,False,70000000,...,Adventure,Fantasy,None,Warner Bros. Pictures,The Stone Quarry,Atlas Entertainment,Access Entertainment,United States of America,None,None
395,466282,To All the Boys I've Loved Before,7.642,8045,Released,2018-08-16,0,100,False,0,...,Romance,None,None,Awesomeness Films,Overbrook Entertainment,None,None,United States of America,None,None
509,454983,The Kissing Booth,7.229,6926,Released,2018-05-11,0,105,False,0,...,Comedy,None,None,Komixx Entertainment,None,None,None,United Kingdom,None,None
670,766507,Prey,7.762,5821,Released,2022-08-02,0,100,False,65000000,...,Action,Science Fiction,None,20th Century Studios,None,None,None,United States of America,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178356,753513,Not a Choice,0.000,0,Released,2016-10-18,0,10,False,0,...,None,None,None,None,None,None,None,None,None,None
1178363,753524,Westgate Bridge Disaster: The Untold Stories,0.000,0,Released,2020-10-15,0,43,False,0,...,None,None,None,WTFN Entertainment,Had to Be Told Productions,Oceanview Entertainment,None,Australia,None,None
1178364,753525,jazlaansam,0.000,0,Released,None,0,0,False,0,...,None,None,None,None,None,None,None,None,None,None
1178366,753532,Costa Brava Heat,0.000,0,Released,2020-10-10,0,110,True,0,...,None,None,None,Private,None,None,None,None,None,None
1178371,753539,Tame Impala live at Glastonbury 2019,0.000,0,Released,2019-06-29,0,89,False,0,...,None,None,None,None,None,None,None,None,None,None

In [97]:
metadata['total_keywords'] = metadata.apply(lambda row: sum(pd.notna(row[col]) for col in ['keyword_1', 'keyword_2', 'keyword_3', 'keyword_4']), axis=1)
metadata['total_genre'] = metadata.apply(lambda row: sum(pd.notna(row[col]) for col in ['genre_1', 'genre_2', 'genre_3', 'genre_4']), axis=1)
metadata['total_production_company'] = metadata.apply(lambda row: sum(pd.notna(row[col]) for col in ['production_company_1', 'production_company_2', 'production_company_3', 'production_company_4']), axis=1)
metadata['total_production_country'] = metadata.apply(lambda row: sum(pd.notna(row[col]) for col in ['production_country_1', 'production_country_2', 'production_country_3']), axis=1)
metadata

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,budget,...,production_company_2,production_company_3,production_company_4,production_country_1,production_country_2,production_country_3,total_keywords,total_genre,total_production_company,total_production_country
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,...,Syncopy,Warner Bros. Pictures,None,United Kingdom,United States of America,None,4,3,3,2
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,...,Syncopy,Lynda Obst Productions,None,United Kingdom,United States of America,None,4,3,3,2
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,...,Legendary Pictures,Syncopy,Isobel Griffiths,United Kingdom,United States of America,None,4,4,4,2
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,...,Lightstorm Entertainment,20th Century Fox,Ingenious Media,United States of America,United Kingdom,None,4,4,4,2
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,...,None,None,None,United States of America,None,None,4,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178356,753513,Not a Choice,0.000,0,Released,2016-10-18,0,10,False,0,...,None,None,None,None,None,None,0,0,0,0
1178363,753524,Westgate Bridge Disaster: The Untold Stories,0.000,0,Released,2020-10-15,0,43,False,0,...,Had to Be Told Productions,Oceanview Entertainment,None,Australia,None,None,0,1,3,1
1178364,753525,jazlaansam,0.000,0,Released,None,0,0,False,0,...,None,None,None,None,None,None,0,0,0,0
1178366,753532,Costa Brava Heat,0.000,0,Released,2020-10-10,0,110,True,0,...,None,None,None,None,None,None,0,0,1,0
1178371,753539,Tame Impala live at Glastonbury 2019,0.000,0,Released,2019-06-29,0,89,False,0,...,None,None,None,None,None,None,0,0,0,0

In [98]:
metadata.to_parquet('../data/raw/movies_metadata.parquet')

In [102]:
overview = pd.read_parquet("../data/raw/movies_overview.parquet")

In [103]:
ids = set(metadata['id'])

In [104]:
overview = overview[overview['id'].isin(ids)]

In [112]:
overview = overview.drop_duplicates(subset=['id'],keep='first')

In [ ]:
overview.to_parquet("../data/raw/movies_overview.parquet")